#Pentagon numbers

#Problem 44
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

#               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?



import math

def is_pentagon(n):
    c=int((1+math.sqrt(1+24*n))/6)
    pc=c*(3*c-1)/2
    if(pc==n):
        return 1


def find_pairs():
    k=2
    while(1):
        pk=k*(3*k-1)/2
        j=k-1
        while(j>0):
            pj=j*(3*j-1)/2
            d=pk-pj
            s=pk+pj
            if(is_pentagon(d) and is_pentagon(s)):
                print(j,k,pk-pj)
                return
            j-=1
        k+=1
        
print(find_pairs())
        
        

